#sets the name of action
name: CI

#trigger: sets the moment in that job to be executed
on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push' #name of job
    runs-on: ubuntu-latest #OS in that job to be executed
    # strategy:
    #   matrix:
    #     node: [ 20 ]

    steps:
    - uses: actions/checkout@v4 #for job to make pull of project

    # - name: Setup node | ${{ matrix.node }}
    - name: Setup node
      uses: actions/setup-node@v4 #configures the node
      with: #variables of input of action of node
        # node-version: ${{ matrix.node }}
        node-version: 20
        cache: 'yarn'
    - run: yarn
    - run: yarn run test

    - name: Generate tag
      id: generate_tag
      run: | #returns a variable of output with the identification of commit
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: marcostulio99ti/kabuto-ci-api:${{ steps.generate_tag.outputs.sha }},marcostulio99ti/kabuto-ci-api:latest

    # - name: Build docker image
    #   run: docker build -t marcostulio99ti/kabuto-ci-api:${{ steps.generate_tag.outputs.sha }} .

    # - name: Push image
    #   run: docker push marcostulio99ti/kabuto-ci-api:${{ steps.generate_tag.outputs.sha }}