#sets the name of action
name: CI

#trigger: sets the moment in that job to be executed
on:
  push:
    branches:
      - main

#sets the permissions for to read the content of token
permissions:
  id-token: write
  contents: read

#sets the jobs
jobs:
  build:
    name: 'Build and Push' #name of job
    runs-on: ubuntu-latest #OS in that job to be executed

    #sets the steps of job
    steps:
    
    #uses action of github for to make pull of project
    - uses: actions/checkout@v4

    #uses action of github for to configure the node
    - name: Setup node
      uses: actions/setup-node@v4
      with: #variables of input of action
        node-version: 20
        cache: 'yarn'
    
    #install the dependencies of project
    - run: yarn
    
    #executes the test
    - run: yarn run test

    #returns a variable of output with the identification of commit
    - name: Generate tag
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    #uses action of github for to set the AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    #uses action of github for to make the login in Amazon ECR
    - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

    # #uses action of github for to make the login in the Docker Hub
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with: #this variables of input of the action by to be configured in the github
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # #uses action of github for to make build and push of image in the Docker hub
    # - name: Build and push
    #   uses: docker/build-push-action@v6
    #   with:
    #     push: true
    #     tags: marcostulio99ti/kabuto-ci-api:${{ steps.generate_tag.outputs.sha }},marcostulio99ti/kabuto-ci-api:latest

    # #uses commands CLI for to make build of image of Docker
    # - name: Build docker image
    #   run: docker build -t marcostulio99ti/kabuto-ci-api:${{ steps.generate_tag.outputs.sha }} .

    # #uses commands CLI for to make push of image in the Docker hub
    # - name: Push image
    #   run: docker push marcostulio99ti/kabuto-ci-api:${{ steps.generate_tag.outputs.sha }}